notifications:
  email:
    on_success: never
    on_failure: change

os:
  - linux
  - osx

node_js:
  - 10
  - 9
  - 8

script: npm test

sudo: false

language: node_js

env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1
